defaults:
  - egovlp_internvideo
  - _self_

additional_feature_type: 'llava'
d_env: 384
llava:
  # llava_dir: '/local_datasets/ego4d_data/v2/llava-v1.6-34b/'
  llava_dir: '/local_datasets/ego4d_data/v2/features/llava-v1.6-34b-cross-encoded'
  scope: 'global'  # 'global', 'local', 'both' -> fixed to global
  load_feature: True
  feature_aggregation: 'cross'  # 'init', 'answer', 'all', 'sentence', 'cross'
