defaults:
  - egovlp_internvideo
  - _self_

additional_feature_type: 'llava'
llava:
  llava_dir: '/local_datasets/ego4d_data/v2/llava-v1.6-34b/'
  scope: 'global'  # 'global', 'local', 'both'
  # target_stride_sec_global: 30.
  # target_stride_sec_local: 10.
  load_feature: True
  feature_aggregation: 'init'  # 'init', 'answer', 'all'
  # load_capion: False
  # load_partial: 700  # 700 clips out of 2017(v2) clips as llava extraction has not been finished
